source "https://rubygems.org/"

gem "capybara" , "3.33.0"
gem "cucumber" , "3.1.2"
gem "ffi"
gem "os" , "1.1.0"
gem "pg", "1.1.4"
gem "report_builder"
gem "rspec" , "3.9.0"
gem "selenium-webdriver" , "3.142.7"
